/* 1° NESSA PRIMEIRA PARTE EU PEGO ELEMENTOS QUE ESTÃO DENTRO UM ELEMENTO "LI" */

// É IMPORTANTE LEMBRAR QUE ESSAS QUERY VEM EM FORMATO DE ARRAY, MAS NÃO ESTÃO INSERIDOS DENTRO UM ARRAY.

// AO EXECUTAR O QUERYSELECTOR EM UMA LISTA COMO O EXEMPLO A ABAIXO ELE IRÁ RETORNAR O PRIMEIRO ELEMENTO.
const item1 = document.querySelector("li");
console.log("PRIMEIRO ELEMENTO DO LI");
console.log(item1);

// AO EXECUTAR O QUERYSELECTORALL SÃO ESTRAIDOS TODOS OS DADOS DO DETERMINAR LOCAL ESPECIFICADO 
console.log("TODOS OS ELEMENTOS LI");
const itens = document.querySelectorAll("li");
console.log(itens);

// USANDO O INNERHTML VOCÊ RETORNA OS DADOS CONTIDOS NAQUELE ITEM EM ESPEFICO
console.log("BUSCANDO O CONTEÚDO DENTO DO PRIMEIRO LI USANDO O QUERYSELECTOR");
console.log(item1.innerHTML);

// RETORNA O CÓDIGO HTML DE INSERÇÃO DO PRIMEIRO ITEM QUE FOI REQUISITADO NO QUERYSELECTOR
console.log("MOSTRANDO O CÓDIGO DO PRIMEIRO ELEMENTO LI BUSCADO PELO QUERYSELECTOR");
console.log(item1.outerHTML);

/* 2° NESSA SEGUNDA PARTE VOU PEGAR ELEMENTOS COM BASE NO USO DE UMA CLASSES QUE ELES UTILIZARAM, DESTA FORMA É COMO UM RASTREIO */

// BUSCANDO CARDS NO CONTEXTO DO HTML CRIADO
const card1 = document.querySelector(".card");
console.log("EXIBINDO O PRIMEIRO CADE BUSCADO PELO QUERYSELECTOR, CONSULTA BASEADA EM QUEM ESTAVA USANDO A CLASS (CARD) ");
console.log(card1);

// MOSTRANDO O CONTEÚDO DO CARD USANDO O INNTERHTML
console.log("CONTEÚDO DO CARD");
console.log(card1.innerHTML);

// MOSTRANDO O CÓDIGO HTML DO CARD1 USANDO O OUTERHTML
console.log("CÓDIGO HTML DO CARD");
console.log(card1.outerHTML);

/* 3° NA TERCEIRA PARTE IREMOS MANIPULAR O DOM E FAZER ALGUNS ACRÉSCIMO DE CONTEÚDO NOS ELEMENTOS SELECIONADOS */

// ACRESCENTANDO "DESCRIÇÃO" AO CARD1 USANDO ANTERIORMENTE
const paragrafo = document.createElement("p");
paragrafo.innerHTML = "Descrição";
card1.appendChild(paragrafo);

// ADICIONANDO UMA BORDA/CLASSE QUE CONTÉM A BORDA A DIV POR MEIO DA MANIPULAÇÃO DO DOM
card1.classList.add("super-border");

// EXIBINDO TODAS AS DIV QUE TEM A CLASS ".card"
/* MÉTODO RECENETE */ const cards = document.querySelectorAll(".card");
// MÉTODO ANTIGO const cards = document.getElementsByClassName("card");
console.log("EXIBINDO TODAS AS DIV QUE TEM A CLASS (.card)");
console.log(cards);

// CRIANDO UM ARRAY PARA MANIPULAR DE OUTRA FORMA OS ELEMENTOS QUE TEM A CLASS "CARD"
console.log("EXIBINDO AS DIV'S POR MEIO DE UM ARRAY, QUE CONTÉM O CLASS (.CARD)");
Array.from(cards).map( exibir => {
    console.log(exibir);
});


// IMPRIMINDO O CONTEÚDO DE ELEMENTOS QUE TEM A CLASS "CARD"
console.log("IMPRIMINDO O CONTEÚDO DE ELEMENTOS QUE TEM A CLASS (.card)");
Array.from(cards).map( ixibir => {
    console.log(ixibir.innerHTML);
});
